language: c
os: osx
script: 
  - make && make test
  - gcov c4.c arithmetic.c

sudo: required

# linux
# before_install:
#   - sudo apt-get install -y gcc-multilib

after_success:
  - bash <(curl -s https://codecov.io/bash)

# vim: et:ts=2:sw=2:
